<a href="https://colab.research.google.com/github/yh08037/ABR_mentoring/blob/master/ABR_mentoring_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ABR 멘토링 1주차
## 1. Python 기본 문법
### 1) Hello world!

In [4]:
print('hello world!')

hello world!


### 2) if문 : 조건문(흐름 제어)



In [0]:
n = 10

In [6]:
if n > 5 :
    print('5보다 큽니다.')

else:
    print('5보다 작거나 같습니다.')

5보다 큽니다.


In [0]:
score = 85

In [0]:
if score >= 90:
    grade = 'A'

elif score >= 80:
    grade = 'B'

elif score >= 70:
    grade = 'C'

else:
    grade = 'F'

In [9]:
grade

'B'

### 3) for문 : 반복문
반복 횟수가 정해져 있을 때!

In [14]:
list(range(10)) # 0 ~ 10-1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
for i in range(10): # 0 ~ 10-1
    print(i)

0
1
2
3
4
5
6
7
8
9


In [18]:
list(range(1, 11)) # 1 ~ 11-1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [25]:
for i in range(10):
    for j in range(10-i):
        print('*', end='')
    print()

**********
*********
********
*******
******
*****
****
***
**
*


### while문 : 반복문
반복 횟수가 정해져 있지 않고, 그 대신 반복을 끝낼 조건이 있을 때!

In [28]:
n = 0

while n < 10:
    print(n)
    n += 1

0
1
2
3
4
5
6
7
8
9


### list, tuple : 나열형
순서가 있는 데이터들의 나열

In [0]:
lst = [1, 2, 3, 4, 5]

In [30]:
type(lst)

list

In [0]:
tpl = (1, 2, 3, 4, 5)

In [32]:
type(tpl)

tuple

In [0]:
lst.append(6)

In [34]:
lst

[1, 2, 3, 4, 5, 6]

In [59]:
[1, 'abcdef', 3.14, [1,2, 3 ,4], (4, 3)]

[1, 'abcdef', 3.14, [1, 2, 3, 4], (4, 3)]

In [0]:
# 2차원 리스트
lst = [[1, 2],
       [3, 4]]

In [62]:
type(lst)

list

#### index : 나열형의 변수내에서 특정 값의 위치
indexing : 인덱스를 통해서 나열형 변수 내의 특정 값을 가져오는 것

In [0]:
a = [7, 34, 9, 6, 2, 50]

In [40]:
len(a)

6

In [38]:
for n in a:
    print(n)

7
34
9
6
2
50


In [39]:
for idx in range(len(a)):
    print(a[idx])

7
34
9
6
2
50


#### unpacking : tuple을 복사


In [0]:
x = 1
y = 2

In [0]:
x, y = 1, 2     # tuple이다!

In [0]:
(x, y) = (1, 2)

### function


In [0]:
def printInfo(name, age):

    print('이름 : %s, 나이 : %d' %(name, age))
    print('이름 : {}, 나이 : {}'.format(name, age))

In [53]:
printInfo('김도훈', 23)

이름 : 김도훈, 나이 : 23
이름 : 김도훈, 나이 : 23


In [51]:
printInfo('노규원', ???)

이름 : 김도훈, 나이 : 23


## 2. Jupyter Notebook 기본 사용법

ctrl + enter : 선택된 셀을 실행한다.

shift + enter : 선택된 셀을 실행하고 나서 다음 셀로 이동

ctrl + f9 : 전체 셀을 한번에 실행

## 3. numpy 기본 사용법

In [0]:
import numpy as np

In [55]:
np.__version__

'1.18.2'

### 행렬 만드는 방법

In [0]:
lst = [[1, 2],
       [3, 4]]
a = np.array(lst)
# a = np.asarray(lst)

In [64]:
a

array([[1, 2],
       [3, 4]])

In [65]:
type(a)

numpy.ndarray

### 행렬 곱을 하는 방법

In [0]:
b = np.array([[5, 6, 7],
              [8, 9, 10]])

In [0]:
c = np.matmul(a, b)

In [68]:
c

array([[21, 24, 27],
       [47, 54, 61]])

In [0]:
c = a @ b

In [71]:
c

array([[21, 24, 27],
       [47, 54, 61]])

### 행렬 전치

In [0]:
d = np.transpose(b)

In [73]:
d

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

$$
\text{traspose of A} : A^T
$$

In [0]:
d = b.T

In [75]:
d

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### 역행렬 

In [0]:
e = np.linalg.inv(a)

In [77]:
e

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### numpy 행렬의 indexing

In [78]:
d[1,0]

6

In [79]:
d[:,0]

array([5, 6, 7])

In [80]:
d[2,:]

array([ 7, 10])